import {Compass} from './north-compass';
import {isTextEditing} from './use-project-history';
import {reshapeRegion} from './reshape-region';
import {applyRegionForm,type RegionForm} from './region-form';
import { Icon } from './workbench-ui';
import { useEffect, useRef, useState } from 'react';
import type { BaseImage } from './base-image';
import { corners, overlaps, type Point, type Rect } from './domain';
import { newRoof, roofFromPrevious, roofRect, toLocal, worldObstacle, type RoofDesign } from './roof-project';
import { rectangleFromThree, metricRect, worldToImage, containsRect, imageToWorld } from './drawing-geometry';
import { usePdfPatch } from './pdf-patch';
type View={x:number;y:number;width:number;height:number;viewportHeight?:number};
function PdfDetail({base,view,pixels}:{base:BaseImage;view:View;pixels:number}){
 const patch=usePdfPatch(base,view,pixels);
 return patch?<image href={patch.url} {...patch.view} pointerEvents="none"/>:null;
}
export function ImageEditor({imageOverlays=[],obstacleHeight=1,onObstacleHeight,onUndo,onRedo,canUndo,canRedo,base,roofs,activeId,onBase,onRoofs,onActive,onClose,initialView,onViewClose,initialTool,initialForm,intent='create',onCalibrated}:{imageOverlays?:import('./image-overlays').ImageOverlay[];obstacleHeight?:number;onObstacleHeight?:(height:number)=>void;onUndo:()=>void;onRedo:()=>void;canUndo:boolean;canRedo:boolean;onCalibrated?:()=>void;intent?:'create'|'reshape'|'scale'|'obstacle'|'keepout';initialForm?:RegionForm;initialTool?:'roof'|'obstacle'|'keepout'|'scale';initialView?:View;onViewClose?:(v:View)=>void;base:BaseImage;roofs:RoofDesign[];activeId:string;onBase:(b:BaseImage)=>void;onRoofs:(r:RoofDesign[])=>void;onActive:(id:string)=>void;onClose:()=>void}){
 const [northSelecting,setNorthSelecting]=useState(false),[northAngle,setNorthAngle]=useState(base.northAngle??0),[northPoints,setNorthPoints]=useState<Point[]>([]);
 const [redraw,setRedraw]=useState(false);
 const [edited,setEdited]=useState<Rect>();
 const resize=useRef<{rect:Rect;index:number;edge:boolean}|undefined>(undefined);
 const [continuous,setContinuous]=useState(false);
 const finish=()=>{onViewClose?.({...view,viewportHeight:svg.current?.clientHeight});onClose();};
 const [form,setForm]=useState<RegionForm|undefined>(initialForm);
 const [tool,setTool]=useState<'scale'|'roof'|'obstacle'|'keepout'|'select'>(base.metersPerPixel?(initialTool??'roof'):'scale');
 const [points,setPoints]=useState<Point[]>([]),[hover,setHover]=useState<Point>(),[distance,setDistance]=useState(''),[armed,setArmed]=useState(false),[notice,setNotice]=useState(base.metersPerPixel?'先点一条边的两个端点，再点第三点确定宽度':'先输入实际长度，再开始标定');
 const [pointRedo,setPointRedo]=useState<Point[]>([]),[editRedo,setEditRedo]=useState<Rect>();
 const undo=()=>{if(points.length){setPointRedo(p=>[...p,points[points.length-1]]);setPoints(p=>p.slice(0,-1));}else if(edited){setEditRedo(edited);resize.current=undefined;setEdited(undefined);}else{onUndo();setNotice('已撤销上一步');}};
 const redo=()=>{if(pointRedo.length){setPoints(p=>[...p,pointRedo[pointRedo.length-1]]);setPointRedo(p=>p.slice(0,-1));}else if(editRedo){setEdited(editRedo);setEditRedo(undefined);}else onRedo();};
 const keyboard=useRef({undo,redo});keyboard.current={undo,redo};
 const svg=useRef<SVGSVGElement>(null),space=useRef(false),pan=useRef<{x:number;y:number;view:View}|undefined>(undefined);
 const [view,setView]=useState<View>(initialView??{x:0,y:0,width:base.width,height:base.height}),[pixels,setPixels]=useState(0);
 const unit=view.width/Math.max(1,pixels),active=roofs.find(r=>r.id===activeId)??roofs[0];
 const fit=()=>{const s=svg.current;if(!s)return;const aspect=s.clientWidth/Math.max(1,s.clientHeight),height=Math.max(base.height,base.width/aspect)*1.04,width=height*aspect;setPixels(s.clientWidth);setView({x:(base.width-width)/2,y:(base.height-height)/2,width,height});};
 useEffect(()=>{if(!initialView)fit();else if(svg.current){const h=svg.current.clientHeight,height=initialView.height*h/(initialView.viewportHeight??h),width=height*svg.current.clientWidth/Math.max(1,h);setView({...initialView,x:initialView.x+(initialView.width-width)/2,y:initialView.y+(initialView.height-height)/2,width,height});}const obs=new ResizeObserver(()=>{const s=svg.current;if(!s)return;setPixels(s.clientWidth);setView(v=>{const width=v.height*s.clientWidth/Math.max(1,s.clientHeight);return {...v,x:v.x+(v.width-width)/2,width};});});if(svg.current)obs.observe(svg.current);return()=>obs.disconnect();},[base.width,base.height]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(isTextEditing(e.target))return;if((e.ctrlKey||e.metaKey)&&!e.altKey&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();if(e.shiftKey||e.key.toLowerCase()==='y')keyboard.current.redo();else keyboard.current.undo();return;}if(e.code==='Space'){space.current=true;e.preventDefault();}if(e.key==='Escape'){setPointRedo([]);setEditRedo(undefined);resize.current=undefined;setEdited(undefined);setPoints([]);setHover(undefined);setArmed(false);setNotice('已取消当前绘制');}if(e.key==='Backspace'){e.preventDefault();setPoints(p=>p.slice(0,-1));}};const up=()=>{space.current=false;};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',up);};},[]);
 useEffect(()=>{const s=svg.current;if(!s)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const box=s.getBoundingClientRect(),u=(e.clientX-box.left)/box.width,v=(e.clientY-box.top)/box.height;setView(old=>{const width=Math.max(base.width/80,Math.min(base.width*3,old.width*Math.exp(Math.max(-150,Math.min(150,e.deltaY))*.002)));const factor=width/old.width;return {x:old.x+u*old.width*(1-factor),y:old.y+v*old.height*(1-factor),width,height:old.height*factor};});};s.addEventListener('wheel',wheel,{passive:false});return()=>s.removeEventListener('wheel',wheel);},[base.width]);
 const pos=(e:React.PointerEvent)=>{const m=svg.current?.getScreenCTM();if(!m)return null;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return {x:p.x,z:p.y};};
 function choose(t:typeof tool){setPointRedo([]);if(t==='roof')setForm(active.pitch?.kind??'flat');setTool(t);setPoints([]);setHover(undefined);setArmed(false);setNotice(t==='scale'?'输入实际长度，再开始标定':t==='select'?'点击屋面选择':'先点一条边的两个端点，再点第三点确定宽度');}
 function commitScale(){const d=Math.hypot(points[1].x-points[0].x,points[1].z-points[0].z);if(d<2){setNotice('两点过近，请选择较长的已知尺寸');return;}const k=Number(distance)/d;if(!Number.isFinite(k)||k<.000001||k>10000){setNotice('比例尺超出范围，请重新输入实际长度');return;}
  if(base.metersPerPixel){const ratio=k/base.metersPerPixel;const next=roofs.map(r=>({...r,x:r.x*ratio,z:r.z*ratio,roof:{width:r.roof.width*ratio,depth:r.roof.depth*ratio},obstacles:r.obstacles.map(o=>({...o,x:o.x*ratio,z:o.z*ratio,width:o.width*ratio,depth:o.depth*ratio})),arrays:[],previous:null,layoutSignature:''}));if(next.some(r=>r.roof.width<2||r.roof.depth<2||r.roof.width>200||r.roof.depth>200)){setNotice('标定后屋面尺寸超出 2–200m，请核对实际长度');return;}onRoofs(next);}
  onBase({...base,metersPerPixel:k});setPoints([]);setArmed(false);setTool(initialTool??'roof');setNotice('比例尺已确认');if(intent==='scale'){setNorthSelecting(true);setNorthPoints([]);setNotice('指定北方向：先点起点，再点朝北的一点；也可直接确认上方为北');}
 }
 function point(p:Point){if(northSelecting){if(northPoints.length!==1){setNorthPoints([p]);}else{const a=northPoints[0];if(Math.hypot(p.x-a.x,p.z-a.z)<2)return;setNorthPoints([a,p]);setNorthAngle((Math.atan2(p.x-a.x,-(p.z-a.z))*180/Math.PI+360)%360);}return;}setEditRedo(undefined);setPointRedo([]);if(intent==='reshape'&&!redraw)return;if(p.x<0||p.z<0||p.x>base.width||p.z>base.height)return;
  if(tool==='select'){const w=imageToWorld(p,base);const hit=[...roofs].reverse().find(r=>containsRect(roofRect(r),{...w,width:0,depth:0,yaw:0}));if(hit)onActive(hit.id);return;}
  if(tool==='scale'){if(!armed){setNotice('请先输入实际长度，点击“开始标定”');return;}setPoints(prev=>prev.length>=2?[p]:[...prev,p]);return;}
  if(!base.metersPerPixel)return;if(points.length<2){setPoints([...points,p]);return;}
  const draft=rectangleFromThree(points[0],points[1],p);if(!draft){setNotice('宽度太小，请重新选择第三点');return;}const r=metricRect(draft,base);
  if(corners(draft).some(p=>p.x<0||p.z<0||p.x>base.width||p.z>base.height)){setNotice('轮廓超出图纸，请重新选择第三点');return;}
  if(tool==='roof'){
   if(r.width<2||r.depth<2||r.width>200||r.depth>200){setNotice('屋面边长需在 2–200m 之间');return;}
   if(intent==='reshape'){try{const next=reshapeRegion(roofs,activeId,r);onRoofs(next);onActive(activeId);finish();}catch(e){setNotice((e as Error).message);}return;}
   const existing=base.frame?roofs:[];
   if(existing.length>=50){setNotice('当前最多支持 50 个屋面');return;}
   if(existing.some(o=>overlaps(roofRect(o),r))){setNotice('与已有屋面重叠，请重新圈定');return;}
   const prefix='屋面';let n=1;while(existing.some(r=>r.name===`${prefix} ${n}`))n++;
   let created={...roofFromPrevious(active,`${prefix} ${n}`),x:r.x,z:r.z,yaw:r.yaw,roof:{width:r.width,depth:r.depth}};
   if(form)created=applyRegionForm(created,form);
   onRoofs([...existing,created]);onActive(created.id);onBase({...base,frame:{x:0,y:0,width:base.width,height:base.height}});setNotice(`${created.name} 已添加`);if(!continuous){finish();return;}
  }else{
   if(!containsRect(roofRect(active),r)){setNotice('障碍物须位于当前选中屋面内');return;}
   if(active.obstacles.length>=100){setNotice('当前屋面障碍物已达 100 个');return;}
   if(r.width<.2||r.depth<.2){setNotice('障碍物边长至少 0.2m');return;}
   const o={...r,...toLocal(r,active),yaw:r.yaw-active.yaw,id:crypto.randomUUID(),kind:tool==='keepout'?'keepout' as const:'obstacle' as const,name:`${tool==='keepout'?'禁布区':'障碍物'} ${active.obstacles.length+1}`,height:tool==='keepout'?0:obstacleHeight};
   onRoofs(roofs.map(s=>s.id===active.id?{...s,obstacles:[...s.obstacles,o]}:s));setNotice(`已添加到 ${active.name}`);
  }
  setPoints([]);
 }
 const editing=intent==='reshape'&&!redraw;
 const applyEdit=()=>{if(!edited){finish();return;}try{const rect=imageRect(edited);if(corners(rect).some(p=>p.x<0||p.z<0||p.x>base.width||p.z>base.height))throw new Error('轮廓超出图纸');onRoofs(reshapeRegion(roofs,activeId,edited));finish();}catch(e){setNotice((e as Error).message);}};
 const draft=points.length===2&&hover&&tool!=='scale'?rectangleFromThree(points[0],points[1],hover):null;
 const color=(tool==='obstacle'||tool==='keepout')?'#dc4c26':'#1478db';
 const poly=(r:Rect)=>corners(r).map(p=>`${p.x},${p.z}`).join(' ');
 const imageRect=(r:Rect):Rect=>({...r,...worldToImage(r,base),width:r.width/base.metersPerPixel!,depth:r.depth/base.metersPerPixel!});
 const marker=(p:Point,i:number)=><g key={i} pointerEvents="none"><circle cx={p.x} cy={p.z} r={6*unit} fill="white" stroke="#162b43" strokeWidth={2} vectorEffect="non-scaling-stroke"/><circle cx={p.x} cy={p.z} r={2*unit} fill={color}/></g>;
 const label=(p:Point,text:string)=><g transform={`translate(${p.x} ${p.z}) scale(${unit})`} pointerEvents="none"><rect x={-text.length*3.5-8} y={-25} width={text.length*7+16} height={21} rx={4} fill="white" stroke="#33465e" strokeWidth={1}/><text y={-11} textAnchor="middle" fontSize={12} fill="#17344a">{text}</text></g>;
 const lineEnd=points.length===1?hover:points[1];
 const format=(d:number)=>base.metersPerPixel?`${(d*base.metersPerPixel).toFixed(2)} m`:`${d.toFixed(1)} px`;
 return <div className="image-editor" role="dialog" aria-label="底图标定与绘制">
  <div className="image-tools grouped-drawing-tools">{northSelecting?<div className="north-controls"><strong>指定北方向</strong><button onClick={()=>{setNorthAngle(0);setNorthPoints([]);}}>上方为北</button><label>顺时针 °<input aria-label="北向角度" type="number" min="0" max="359.9" step="0.1" value={Number(northAngle.toFixed(1))} onChange={e=>{const n=Number(e.target.value);if(e.target.value&&Number.isFinite(n)&&n>=0&&n<360){setNorthAngle(n);setNorthPoints([]);}}}/></label><button className="drawing-done" onClick={()=>{onBase({...base,northAngle});finish();onCalibrated?.();}}>确认北向</button></div>:<>  {tool==='scale'&&<div className="calibration-inline">   {tool==='scale'&&<><label>长度 m<input aria-label="标定真实距离 m" type="number" min=".01" value={distance} disabled={armed} onChange={e=>setDistance(e.target.value)}/></label>{!armed?<button disabled={!Number.isFinite(Number(distance))||Number(distance)<=0} onClick={()=>{setArmed(true);setPoints([]);setNotice('点击已知尺寸的两个端点');}}>开始标定</button>:<button disabled={points.length!==2} onClick={commitScale}>确认标定</button>}{base.frame&&<span>重标定后需重新布置</span>}</>}</div>}
   <div className="drawing-tool-group" role="group" aria-label="绘制">{([['roof','圈屋面','roof'],['obstacle','障碍物','box'],['keepout','禁布区','frame']] as const).filter(([id])=>!editing&&id===initialTool).map(([id,label,icon])=><button key={id} disabled={(id==='roof')?!base.metersPerPixel:!base.frame} className={tool===id?'selected':''} aria-pressed={tool===id} onClick={()=>choose(id)}><Icon name={icon}/>{label}</button>)}</div>
   {tool==='obstacle'&&<label className="obstacle-height-input">高度 m<input aria-label="新建障碍物高度 m" type="number" min="0.2" max="30" step="0.1" value={obstacleHeight} onChange={e=>{const h=Number(e.target.value);if(h>=.2&&h<=30)onObstacleHeight?.(h);}}/></label>}
   {intent==='create'&&(tool==='roof')&&<select aria-label="绘制区域形式" value={form??(active.pitch?.kind??'flat')} onChange={e=>setForm(e.target.value as RegionForm)}>{[['flat','平屋面'],['single','单坡屋面'],['gable','双坡屋面']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>}
   {intent!=='reshape'&&intent!=='scale'&&base.frame&&<div className="drawing-tool-group" role="group" aria-label="当前屋面"><select aria-label="绘图当前屋面" value={active.id} onChange={e=>{onActive(e.target.value);setPoints([]);}}>{roofs.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className={`icon-button ${tool==='select'?'selected':''}`} title="在图纸中选择屋面" aria-label="选择屋面" aria-pressed={tool==='select'} onClick={()=>choose('select')}><Icon name="pointer"/></button></div>}
   <div className="drawing-tool-group" hidden={tool==='scale'} role="group" aria-label="辅助操作"><button className="icon-button" onClick={fit} title="显示全图" aria-label="显示全图"><Icon name="frame"/></button><button className="icon-button" disabled={!canUndo&&!points.length&&!edited} onClick={undo} title="撤回上次轮廓操作" aria-label="撤回轮廓"><Icon name="reset"/></button><button className="icon-button" disabled={!canRedo&&!pointRedo.length&&!editRedo} onClick={redo} title="重做 · Ctrl+Shift+Z" aria-label="重做轮廓"><Icon name="redo"/></button>
   {points.length>0&&<><button className="icon-button" onClick={()=>setPoints(p=>p.slice(0,-1))} title="退一点 · Backspace" aria-label="退一点"><Icon name="back"/></button><button className="icon-button" onClick={()=>{setPoints([]);setArmed(false);setHover(undefined);}} title="取消绘制 · Esc" aria-label="取消绘制"><Icon name="close"/></button></>}
   <details className="drawing-more"><summary title="比例尺与屋面管理" aria-label="更多绘图操作"><Icon name="settings"/></summary><div><button className={tool==='scale'?'selected':''} onClick={e=>{choose('scale');e.currentTarget.closest('details')?.removeAttribute('open');}}>设置比例尺</button>{tool==='select'&&base.frame&&<button onClick={()=>{const next=roofs.filter(r=>r.id!==active.id);if(!next.length){const placeholder=roofFromPrevious(active,'屋面 1');onRoofs([placeholder]);onActive(placeholder.id);onBase({...base,frame:undefined});}else{onRoofs(next);onActive(next[0].id);}setNotice('已移除屋面，可撤回');}}>移除当前屋面</button>}</div></details></div>
   {intent==='create'&&(tool==='roof')&&<label className="checkline"><input type="checkbox" checked={continuous} onChange={e=>setContinuous(e.target.checked)}/>连续新增</label>}
   {intent==='reshape'&&<><span>修改：{active.name}</span><button onClick={()=>{setRedraw(v=>!v);setEdited(undefined);setPoints([]);setNotice(redraw?'拖动角点或边调整轮廓':'先点一条边的两个端点，再点第三点确定宽度');}}>{redraw?'返回拖动调整':'重新绘制'}</button><button onClick={finish}>取消</button></>}
   <button className="icon-button" hidden={tool!=='scale'} title="退出标定" aria-label="退出标定" onClick={finish}><Icon name="close"/></button><button className="drawing-done icon-button" hidden={tool==='scale'} title="完成并返回" aria-label="完成并返回" onClick={editing?applyEdit:finish}><Icon name="check"/></button>
  </>}</div>
  <Compass angle={northSelecting?northAngle:base.northAngle??0}/>

  <div className="drawing-status" title="滚轮缩放 · 中键 / 空格拖动"><span role="status">{editing&&notice==='先点一条边的两个端点，再点第三点确定宽度'?'拖动角点或边调整轮廓，完成后应用':notice}</span><span>滚轮缩放 · 中键 / 空格拖动</span></div>
  <svg ref={svg} viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} aria-label="底图绘制画布" preserveAspectRatio="none" style={{cursor:editing?"default":"crosshair",touchAction:"none"}} onContextMenu={e=>e.preventDefault()} onPointerDown={e=>{if(e.button===1||e.button===0&&space.current){e.preventDefault();pan.current={x:e.clientX,y:e.clientY,view};e.currentTarget.setPointerCapture(e.pointerId);return;}if(e.button===0){const p=pos(e);if(p)point(p);}}} onPointerMove={e=>{if(resize.current){setEditRedo(undefined);const p=pos(e);if(!p)return;const w=imageToWorld(p,base),{rect,index,edge}=resize.current,c=Math.cos(rect.yaw),sn=Math.sin(rect.yaw),dx=w.x-rect.x,dz=w.z-rect.z,lx=dx*c-dz*sn,lz=dx*sn+dz*c;let left=-rect.width/2,right=rect.width/2,top=-rect.depth/2,bottom=rect.depth/2;if(edge?index===3:index===0||index===3)left=Math.min(lx,right-2);if(edge?index===1:index===1||index===2)right=Math.max(lx,left+2);if(edge?index===0:index===0||index===1)top=Math.min(lz,bottom-2);if(edge?index===2:index===2||index===3)bottom=Math.max(lz,top+2);const x=(left+right)/2,z=(top+bottom)/2;setEdited({...rect,x:rect.x+x*c+z*sn,z:rect.z-x*sn+z*c,width:right-left,depth:bottom-top});return;}if(pan.current){const p=pan.current;setView({...p.view,x:p.view.x-(e.clientX-p.x)*p.view.width/e.currentTarget.clientWidth,y:p.view.y-(e.clientY-p.y)*p.view.height/e.currentTarget.clientHeight});}else{const p=pos(e);if(p)setHover(p);}}} onPointerUp={e=>{resize.current=undefined;pan.current=undefined;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{resize.current=undefined;setEdited(undefined);pan.current=undefined;}}>
   <image href={base.url} width={base.width} height={base.height} pointerEvents="none"/>{base.pdfSource&&<PdfDetail base={base} view={view} pixels={pixels}/>}
   {base.metersPerPixel&&imageOverlays.filter(o=>o.visible).map(o=>{const p=worldToImage(o,base),k=base.metersPerPixel!;return <image key={o.id} href={o.url} x={p.x-o.width/k/2} y={p.z-o.depth/k/2} width={o.width/k} height={o.depth/k} opacity={o.opacity} transform={`rotate(${-o.yaw*180/Math.PI} ${p.x} ${p.z})`} pointerEvents="none"/>;})}
   {northSelecting&&northPoints.length>0&&<g pointerEvents="none"><defs><marker id="north-tip" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0 10 5 0 10Z" fill="#397fae"/></marker></defs><line x1={northPoints[0].x} y1={northPoints[0].z} x2={(northPoints[1]??hover??northPoints[0]).x} y2={(northPoints[1]??hover??northPoints[0]).z} stroke="#397fae" strokeWidth={2*unit} markerEnd="url(#north-tip)"/></g>}
   <g pointerEvents="none">{base.frame&&base.metersPerPixel&&roofs.map(r=>{const rect=imageRect(r.id===active.id&&edited?edited:roofRect(r)),selected=r.id===active.id;return <g key={r.id}><polygon points={poly(rect)} fill={selected?'#1478db15':'#1478db08'} stroke="white" strokeWidth={5} vectorEffect="non-scaling-stroke"/><polygon points={poly(rect)} fill="none" stroke={selected?'#1478db':'#417f8b'} strokeWidth={2} vectorEffect="non-scaling-stroke"/>{selected&&corners(rect).map(marker)}{label(corners(rect)[0],r.name)}{r.obstacles.map(o=>{const rect=imageRect(worldObstacle(o,r));return <g key={o.id}><polygon points={poly(rect)} fill={o.kind==='keepout'?"#cc386344":"#df582833"} stroke="white" strokeWidth={5} vectorEffect="non-scaling-stroke"/><polygon points={poly(rect)} fill="none" stroke={o.kind==='keepout'?"#b83761":"#dc4c26"} strokeDasharray={o.kind==='keepout'?"6 3":undefined} strokeWidth={2} vectorEffect="non-scaling-stroke"/>{selected&&corners(rect).map(marker)}</g>;})}</g>;})}
   {draft&&<><polygon points={poly(draft)} fill="#1478db12" stroke="white" strokeWidth={5} vectorEffect="non-scaling-stroke"/><polygon points={poly(draft)} fill="none" stroke={color} strokeWidth={2} strokeDasharray="8 5" vectorEffect="non-scaling-stroke"/>{label({x:draft.x,z:draft.z},`${format(draft.width)} × ${format(draft.depth)}`)}</>}
   {points.length>0&&lineEnd&&<><line x1={points[0].x} y1={points[0].z} x2={lineEnd.x} y2={lineEnd.z} stroke="white" strokeWidth={5} vectorEffect="non-scaling-stroke"/><line x1={points[0].x} y1={points[0].z} x2={lineEnd.x} y2={lineEnd.z} stroke={color} strokeWidth={2} strokeDasharray="8 5" vectorEffect="non-scaling-stroke"/>{label({x:(points[0].x+lineEnd.x)/2,z:(points[0].z+lineEnd.z)/2},format(Math.hypot(points[0].x-lineEnd.x,points[0].z-lineEnd.z)))}</>}
   {points.map(marker)}
   </g>
   {editing&&base.metersPerPixel&&(()=>{const rect=edited??roofRect(active),cs=corners(imageRect(rect));const begin=(e:React.PointerEvent,index:number,edge:boolean)=>{if(e.button!==0||space.current)return;e.stopPropagation();resize.current={rect,index,edge};svg.current?.setPointerCapture(e.pointerId);};return <g>{cs.map((p,i)=><line key={'e'+i} x1={p.x} y1={p.z} x2={cs[(i+1)%4].x} y2={cs[(i+1)%4].z} stroke="transparent" strokeWidth={12} vectorEffect="non-scaling-stroke" style={{cursor:'move'}} onPointerDown={e=>begin(e,i,true)}/>)}{cs.map((p,i)=><circle key={i} cx={p.x} cy={p.z} r={7*unit} fill="white" stroke="#1478db" strokeWidth={2} vectorEffect="non-scaling-stroke" style={{cursor:'move'}} onPointerDown={e=>begin(e,i,false)}/>)}</g>;})()}
  </svg>
 </div>;
}
