import {useEffect,useRef,useState} from 'react';
import {Icon} from './workbench-ui';
import {loadDrawing} from './drawing-import';
import {parseImageOverlays,type ImageOverlay} from './image-overlays';
type Props={items:ImageOverlay[];selected:string|null;center:{x:number;z:number};initialWidth:number;onChange:(items:ImageOverlay[])=>void;onSelect:(id:string|null)=>void;onClose:()=>void};
export function ImageOverlayPanel({items,selected,center,initialWidth,onChange,onSelect,onClose}:Props){
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const input=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const current=items.find(o=>o.id===selected),patch=(p:Partial<ImageOverlay>)=>onChange(items.map(o=>o.id===selected?{...o,...p}:o));
 const load=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('请选择 PNG、JPG 或 WebP 图片');if(file.size>8000000)throw new Error('单张图片不超过 8 MB');const image=await loadDrawing(file),width=Math.min(1000,Math.max(5,initialWidth)),o:ImageOverlay={id:crypto.randomUUID(),name:file.name,url:image.url,...center,yaw:0,width,depth:width*image.height/image.width,originalWidth:width,opacity:.55,visible:true};const next=parseImageOverlays([...items,o]);if(!alive.current)return;onChange(next);onSelect(o.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="image-overlay-panel" aria-label="叠加图片设置"><header><strong>叠加图片</strong><button className="icon-button" aria-label="完成图片调整" onClick={onClose}><Icon name="check"/></button></header><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" aria-label="导入叠加图片" onChange={e=>{void load(e.target.files?.[0]);e.target.value='';}}/><button className="overlay-add" disabled={busy||items.length>=8} onClick={()=>input.current?.click()}><Icon name="plus"/>{busy?'正在导入…':'导入图片'}</button>
 <div className="overlay-list">{items.map(o=><div key={o.id} className={o.id===selected?'selected':''}><button aria-label={'调整 '+o.name} onClick={()=>onSelect(o.id)}>{o.name}</button><button className="icon-button" aria-label={(o.visible?'隐藏 ':'显示 ')+o.name} onClick={()=>onChange(items.map(i=>i.id===o.id?{...i,visible:!i.visible}:i))}><Icon name={o.visible?'eye':'eye-off'}/></button></div>)}</div>
 {current&&<div className="overlay-fields"><label className="overlay-opacity">透明度 <output>{Math.round((1-current.opacity)*100)}%</output><input aria-label="图片透明度" type="range" min="0" max="95" step="1" value={Math.round((1-current.opacity)*100)} onChange={e=>patch({opacity:1-Number(e.target.value)/100})}/></label>
 <label>比例 %<input aria-label="图片比例" type="number" min="1" max="10000" value={Number((current.width/current.originalWidth*100).toFixed(1))} onChange={e=>{const n=Number(e.target.value),w=current.originalWidth*n/100,d=w*current.depth/current.width;if(n>0&&w>=.1&&d>=.1&&w<=10000&&d<=10000)patch({width:w,depth:d});}}/></label><label>旋转 °<input aria-label="图片旋转角度" type="number" step="1" value={Number((-current.yaw*180/Math.PI).toFixed(1))} onChange={e=>{const n=Number(e.target.value);if(e.target.value&&Number.isFinite(n))patch({yaw:-n*Math.PI/180});}}/></label>
 <label>宽度 m<input aria-label="叠加图片宽度" type="number" step="0.1" value={Number(current.width.toFixed(2))} onChange={e=>{const w=Number(e.target.value),d=w*current.depth/current.width;if(w>=.1&&w<=10000&&d>=.1&&d<=10000)patch({width:w,depth:d});}}/></label><label>长度 m<input aria-label="叠加图片长度" readOnly value={current.depth.toFixed(2)}/></label>
 <small>拖动图片定位，拖动角点等比缩放</small><button className="overlay-delete" onClick={()=>{onChange(items.filter(o=>o.id!==selected));onSelect(null);}}>删除图片</button></div>}{error&&<p role="alert">{error}</p>}</section>;
}
