import {RoofTypeSelector} from './roof-type-selector';
import type {RoofDesign} from './roof-project';
import type {Obstacle} from './domain';
import {defaultPitch} from './pitched-roof';
import {turnPitch} from './roof-direction';
import {Icon} from './workbench-ui';
type Props={region:RoofDesign;selected?:Obstacle;disabled:boolean;onChange:(patch:Partial<RoofDesign>)=>void;onAdd:(kind:'obstacle'|'keepout'|'building')=>void;onSelect:(id:string|null)=>void;onEdit:(id:string)=>void;onDelete:(id:string)=>void};
export function RegionPanel({region:r,selected,disabled,onChange,onAdd,onSelect,onEdit,onDelete}:Props){
 const number=(label:string,value:number,min:number,max:number,change:(n:number)=>void)=><label className="region-field"><span>{label}</span><input aria-label={label} type="number" step="0.1" min={min} max={max} value={value} disabled={disabled} onChange={e=>{const n=Number(e.target.value);if(e.target.value&&Number.isFinite(n)&&n>=min&&n<=max)change(n);}} onBlur={e=>{e.currentTarget.value=String(value);}}/></label>;
 return <section className="region-panel">
 <section className="region-section"><h2>屋面类型</h2><RoofTypeSelector value={r.pitch?.kind??'flat'} disabled={disabled||!!r.roof.outline} onChange={kind=>{if((r.pitch?.kind??'flat')!==kind)onChange({pitch:kind==='flat'?undefined:{...(r.pitch??defaultPitch),kind},layoutOptions:{...r.layoutOptions,tableRows:Math.min(kind==='gable'?6:3,r.layoutOptions.tableRows??1)},previous:r.arrays,arrays:[]});}}/>{r.roof.outline&&<p className="region-type-note">多边形屋面当前支持平屋面；坡屋面请新建矩形区域。</p>}</section>
 <section className="region-section"><h2>屋面信息{r.pitch&&<button className="icon-button" aria-label={r.pitch.kind==='single'?'旋转坡向':'切换屋脊方向'} disabled={disabled} data-tooltip={r.pitch.kind==='single'?'旋转坡向':'切换屋脊方向'} onClick={()=>onChange({pitch:turnPitch(r.pitch!),previous:r.arrays,arrays:[]})}><Icon name={r.pitch.kind==='gable'?'ridge-direction':'slope-direction'} style={{transform:r.pitch.kind==='gable'&&r.pitch.axis==='x'?'rotate(90deg)':undefined}}/></button>}</h2><div className="region-fields">
 {r.pitch?<>{number('坡度 %',r.pitch.percent,0,100,percent=>onChange({pitch:{...r.pitch!,percent},previous:r.arrays,arrays:[]}))}{number('低檐高 m',r.pitch.eave,1,100,eave=>onChange({pitch:{...r.pitch!,eave},previous:r.arrays,arrays:[]}))}</>:<>{number('屋面高度 m',r.flatHeight??3.5,1,100,flatHeight=>onChange({flatHeight}))}{number('女儿墙高 m',r.wallHeight,0,5,wallHeight=>onChange({wallHeight}))}</>}
 </div></section>
 {(['building','obstacle','keepout'] as const).map(kind=>{const items=r.obstacles.filter(o=>kind==='building'?!!o.topLayout:!o.topLayout&&(o.kind??'obstacle')===kind),label=kind==='building'?'附属建筑':kind==='keepout'?'禁布区':'障碍物';return <section key={kind} className="region-section region-objects"><h2>{label}<span className="object-count">{items.length} 个</span><button className="icon-button" aria-label={'新增'+label} title={'新增'+label} disabled={disabled||r.obstacles.length>=100} onClick={()=>onAdd(kind)}><Icon name="plus"/></button></h2>
 <div className="object-rows">{items.map(o=><div key={o.id} className={'object-row-wrap'+(selected?.id===o.id?' is-selected':'')}>
 <div className="object-row"><button disabled={disabled} className="object-row-select" aria-pressed={selected?.id===o.id} onClick={()=>onSelect(o.id)} onDoubleClick={()=>onEdit(o.id)}>{o.name}{kind!=='keepout'&&<small>高 {o.height.toFixed(1)} m</small>}</button><button className="icon-button object-row-edit" aria-label={'修改'+o.name} title={'修改'+o.name} disabled={disabled} onClick={()=>onEdit(o.id)}><Icon name="edit"/></button><button className="icon-button object-row-delete" aria-label={'删除'+o.name} title={'删除'+o.name} disabled={disabled} onClick={()=>onDelete(o.id)}><Icon name="trash"/></button></div>
 {o.topLayout&&selected?.id===o.id&&<div className="region-fields building-top-fields"><label className="region-field building-top-toggle"><span>顶部布置组件</span><input type="checkbox" checked={o.topLayout.enabled} disabled={disabled} onChange={e=>onChange({obstacles:r.obstacles.map(v=>v.id===o.id?{...v,topLayout:{...o.topLayout!,enabled:e.target.checked}}:v),arrays:r.arrays.filter(a=>a.hostObstacleId!==o.id)})}/></label>{o.topLayout.enabled&&<>{number('顶部倾角 °',o.topLayout.tilt,0,60,tilt=>onChange({obstacles:r.obstacles.map(v=>v.id===o.id?{...v,topLayout:{...o.topLayout!,tilt}}:v)}))}{number('顶部边距 m',o.topLayout.edge,0,20,edge=>onChange({obstacles:r.obstacles.map(v=>v.id===o.id?{...v,topLayout:{...o.topLayout!,edge}}:v)}))}</>}</div>}
 </div>)}</div>
 </section>;})}
 </section>;
}
